databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master
    configured_hdfs_user: hive
    cli_ldap_truststore_path: /etc/ldap/cacerts.jks
    cli_ldap_truststore_password: testldap
    cli_ldap_user_name: DefaultGroupUser
    cli_ldap_user_password: LDAPPass123
    cli_ldap_server_address: https://${databases.presto.host}:8443
